// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/message/user.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{0}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResult struct {
	Ok                   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *AccessToken `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{2}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *LoginResult) GetData() *AccessToken {
	if m != nil {
		return m.Data
	}
	return nil
}

type FormRegister struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormRegister) Reset()         { *m = FormRegister{} }
func (m *FormRegister) String() string { return proto.CompactTextString(m) }
func (*FormRegister) ProtoMessage()    {}
func (*FormRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{3}
}

func (m *FormRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormRegister.Unmarshal(m, b)
}
func (m *FormRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormRegister.Marshal(b, m, deterministic)
}
func (m *FormRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormRegister.Merge(m, src)
}
func (m *FormRegister) XXX_Size() int {
	return xxx_messageInfo_FormRegister.Size(m)
}
func (m *FormRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_FormRegister.DiscardUnknown(m)
}

var xxx_messageInfo_FormRegister proto.InternalMessageInfo

func (m *FormRegister) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *FormRegister) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *FormRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FormRegister) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FormRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FormRegister) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *FormRegister) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterResult struct {
	Ok                   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *AccessToken `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{4}
}

func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (m *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(m, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

func (m *RegisterResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RegisterResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RegisterResult) GetData() *AccessToken {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserData struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{5}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserData) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateUserDataByUserName struct {
	Username             string        `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Data                 *FormRegister `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateUserDataByUserName) Reset()         { *m = UpdateUserDataByUserName{} }
func (m *UpdateUserDataByUserName) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDataByUserName) ProtoMessage()    {}
func (*UpdateUserDataByUserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{6}
}

func (m *UpdateUserDataByUserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDataByUserName.Unmarshal(m, b)
}
func (m *UpdateUserDataByUserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDataByUserName.Marshal(b, m, deterministic)
}
func (m *UpdateUserDataByUserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDataByUserName.Merge(m, src)
}
func (m *UpdateUserDataByUserName) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDataByUserName.Size(m)
}
func (m *UpdateUserDataByUserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDataByUserName.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDataByUserName proto.InternalMessageInfo

func (m *UpdateUserDataByUserName) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserDataByUserName) GetData() *FormRegister {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserDataByUserNameResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserDataByUserNameResult) Reset()         { *m = UpdateUserDataByUserNameResult{} }
func (m *UpdateUserDataByUserNameResult) String() string { return proto.CompactTextString(m) }
func (*UpdateUserDataByUserNameResult) ProtoMessage()    {}
func (*UpdateUserDataByUserNameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{7}
}

func (m *UpdateUserDataByUserNameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserDataByUserNameResult.Unmarshal(m, b)
}
func (m *UpdateUserDataByUserNameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserDataByUserNameResult.Marshal(b, m, deterministic)
}
func (m *UpdateUserDataByUserNameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserDataByUserNameResult.Merge(m, src)
}
func (m *UpdateUserDataByUserNameResult) XXX_Size() int {
	return xxx_messageInfo_UpdateUserDataByUserNameResult.Size(m)
}
func (m *UpdateUserDataByUserNameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserDataByUserNameResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserDataByUserNameResult proto.InternalMessageInfo

func (m *UpdateUserDataByUserNameResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UpdateUserDataByUserNameResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UserName struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserName) Reset()         { *m = UserName{} }
func (m *UserName) String() string { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()    {}
func (*UserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{8}
}

func (m *UserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserName.Unmarshal(m, b)
}
func (m *UserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserName.Marshal(b, m, deterministic)
}
func (m *UserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserName.Merge(m, src)
}
func (m *UserName) XXX_Size() int {
	return xxx_messageInfo_UserName.Size(m)
}
func (m *UserName) XXX_DiscardUnknown() {
	xxx_messageInfo_UserName.DiscardUnknown(m)
}

var xxx_messageInfo_UserName proto.InternalMessageInfo

func (m *UserName) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserDataByUserNameResult struct {
	Ok                   bool      `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *UserData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserDataByUserNameResult) Reset()         { *m = GetUserDataByUserNameResult{} }
func (m *GetUserDataByUserNameResult) String() string { return proto.CompactTextString(m) }
func (*GetUserDataByUserNameResult) ProtoMessage()    {}
func (*GetUserDataByUserNameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_47df16798eebe0b2, []int{9}
}

func (m *GetUserDataByUserNameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserDataByUserNameResult.Unmarshal(m, b)
}
func (m *GetUserDataByUserNameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserDataByUserNameResult.Marshal(b, m, deterministic)
}
func (m *GetUserDataByUserNameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserDataByUserNameResult.Merge(m, src)
}
func (m *GetUserDataByUserNameResult) XXX_Size() int {
	return xxx_messageInfo_GetUserDataByUserNameResult.Size(m)
}
func (m *GetUserDataByUserNameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserDataByUserNameResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserDataByUserNameResult proto.InternalMessageInfo

func (m *GetUserDataByUserNameResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetUserDataByUserNameResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetUserDataByUserNameResult) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AccessToken)(nil), "message.AccessToken")
	proto.RegisterType((*Credentials)(nil), "message.Credentials")
	proto.RegisterType((*LoginResult)(nil), "message.LoginResult")
	proto.RegisterType((*FormRegister)(nil), "message.FormRegister")
	proto.RegisterType((*RegisterResult)(nil), "message.RegisterResult")
	proto.RegisterType((*UserData)(nil), "message.UserData")
	proto.RegisterType((*UpdateUserDataByUserName)(nil), "message.UpdateUserDataByUserName")
	proto.RegisterType((*UpdateUserDataByUserNameResult)(nil), "message.UpdateUserDataByUserNameResult")
	proto.RegisterType((*UserName)(nil), "message.UserName")
	proto.RegisterType((*GetUserDataByUserNameResult)(nil), "message.GetUserDataByUserNameResult")
}

func init() { proto.RegisterFile("protobuf/message/user.proto", fileDescriptor_47df16798eebe0b2) }

var fileDescriptor_47df16798eebe0b2 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xdd, 0xce, 0xd2, 0x40,
	0x10, 0x4d, 0xf9, 0xf8, 0x9d, 0x12, 0x12, 0x37, 0x98, 0x34, 0x12, 0xfc, 0x69, 0xa2, 0xc1, 0x0b,
	0xc0, 0xe8, 0x13, 0x88, 0x0a, 0x37, 0x86, 0x8b, 0x46, 0x6e, 0xbc, 0xc1, 0x81, 0x0e, 0xa5, 0xd2,
	0x76, 0x9b, 0xdd, 0x6d, 0x8c, 0x0f, 0xe6, 0xa3, 0xf8, 0x3e, 0x66, 0xb7, 0x3f, 0x52, 0x0c, 0x12,
	0x63, 0xf2, 0xdd, 0x10, 0xce, 0x99, 0xe9, 0xec, 0x39, 0x67, 0x27, 0x0b, 0xa3, 0x54, 0x70, 0xc5,
	0x77, 0xd9, 0x61, 0x1e, 0x93, 0x94, 0x18, 0xd0, 0x3c, 0x93, 0x24, 0x66, 0x86, 0x65, 0x9d, 0x82,
	0x73, 0x5f, 0x81, 0xfd, 0x76, 0xbf, 0x27, 0x29, 0x3f, 0xf1, 0x13, 0x25, 0xec, 0x19, 0xf4, 0xd1,
	0xc0, 0xad, 0xd2, 0xd8, 0xb1, 0x9e, 0x5a, 0x93, 0x9e, 0x67, 0xe3, 0xef, 0x16, 0xf7, 0x03, 0xd8,
	0xef, 0x04, 0xf9, 0x94, 0xa8, 0x10, 0x23, 0xc9, 0x1e, 0x41, 0x57, 0xcf, 0x4d, 0x30, 0xa6, 0xa2,
	0xbb, 0xc2, 0xba, 0x96, 0xa2, 0x94, 0xdf, 0xb8, 0xf0, 0x9d, 0x46, 0x5e, 0x2b, 0xb1, 0xbb, 0x02,
	0xfb, 0x23, 0x0f, 0xc2, 0xc4, 0x23, 0x99, 0x45, 0x8a, 0x0d, 0xa0, 0xc1, 0x4f, 0x66, 0x40, 0xd7,
	0x6b, 0xf0, 0x13, 0x9b, 0x40, 0xd3, 0x47, 0x85, 0xe6, 0x33, 0xfb, 0xf5, 0x70, 0x56, 0xe8, 0x9d,
	0x9d, 0x89, 0xf5, 0x4c, 0x87, 0xfb, 0xd3, 0x82, 0xfe, 0x92, 0x8b, 0xd8, 0xa3, 0x20, 0x94, 0x8a,
	0x04, 0x1b, 0x03, 0x1c, 0x42, 0x21, 0xd5, 0xf6, 0x4c, 0x53, 0xcf, 0x30, 0x6b, 0x2d, 0x6a, 0x04,
	0xbd, 0x08, 0xcb, 0x6a, 0xa1, 0x4a, 0x13, 0xeb, 0x42, 0x71, 0xe5, 0xe6, 0xee, 0xc2, 0xcd, 0x10,
	0x5a, 0x14, 0x63, 0x18, 0x39, 0x4d, 0x53, 0xc8, 0x41, 0xcd, 0x63, 0xab, 0xee, 0x51, 0xa7, 0x99,
	0x1e, 0x79, 0x42, 0xdb, 0x24, 0x8b, 0x77, 0x24, 0x9c, 0x76, 0x9e, 0xa6, 0xe1, 0xd6, 0x86, 0x62,
	0x0e, 0x74, 0xd0, 0xf7, 0x05, 0x49, 0xe9, 0x74, 0x4c, 0xb5, 0x84, 0xee, 0x17, 0x18, 0x94, 0x96,
	0xae, 0x64, 0xa4, 0x05, 0x09, 0xc1, 0x45, 0xe1, 0x22, 0x07, 0x55, 0x72, 0x77, 0x37, 0x93, 0xfb,
	0x61, 0x41, 0x77, 0x23, 0x49, 0xbc, 0x47, 0x85, 0xf7, 0x9c, 0xda, 0x65, 0x32, 0xad, 0xbf, 0x26,
	0xd3, 0xae, 0x27, 0x83, 0xe0, 0x6c, 0x52, 0x1f, 0x15, 0x95, 0xe2, 0x17, 0xdf, 0xf5, 0xbf, 0x3f,
	0xa4, 0x5c, 0xae, 0xe3, 0xcb, 0xda, 0x4e, 0x3d, 0xac, 0x92, 0x39, 0xdf, 0x9e, 0x22, 0x9a, 0x25,
	0x3c, 0xbe, 0x76, 0xc4, 0xbf, 0x5c, 0x86, 0xfb, 0x22, 0x4f, 0xf8, 0x96, 0x34, 0xf7, 0x2b, 0x8c,
	0x56, 0xa4, 0xfe, 0xef, 0x30, 0xf6, 0xbc, 0x76, 0xf3, 0x0f, 0x2a, 0x7f, 0xe5, 0xd8, 0xdc, 0xdb,
	0xe2, 0xc9, 0xe7, 0xb1, 0x3c, 0xa2, 0xa0, 0xa9, 0x79, 0x0a, 0xe6, 0xe6, 0x77, 0x1a, 0x50, 0x52,
	0xbe, 0x13, 0xbb, 0xb6, 0xa1, 0xde, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x09, 0x8b, 0x59,
	0x42, 0x04, 0x00, 0x00,
}
